version: "3"
services:
  mysql:
    image: mysql:5.7
#    restart: always
    environment:
      MYSQL_DATABASE: 'book'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'zjx'
      # You can use whatever password you like
      MYSQL_PASSWORD: '123456'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '123456'
#      docker-compose默认时区UTC
      TZ: 'Asia/Shanghai'
    ports:
      - '3326:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./data:/var/lib/mysql